#!/usr/bin/env bash
# Bash script to display the content of the current directory in list format
# Display only the part of the name after the first dash

for file in *; do
    if [[ -f $file && ! $file == .* ]]; then
        echo "${file#*-}"
    fi
done
